// Generado por japon/votar/scripts/build_frames.py — NO editar a mano.
// 26 lugares con frame de reel sobre 272. El resto va con card tipográfica.
window.VOTAR_FRAMES = {
 "p-21st-century-museum-of-contemporary-art": "img/DcYZqIYGGrz.webp",
 "p-aomori-museum-of-art": "img/DcSFLx9JD7x.webp",
 "p-benesse-house-museum": "img/DcYZqIYGGrz.webp",
 "p-chanel-ginza": "img/Db-y_xbiEaq.webp",
 "p-chokuritsuenjin": "img/DcPna9ItwPz.webp",
 "p-edo-tokyo-open-air-architectural-museum": "img/Daxni-BS1_r.webp",
 "p-general-store-railyard": "img/DAqbsbnyc_k.webp",
 "p-hachinohe-art-museum": "img/DcSFLx9JD7x.webp",
 "p-hiroshi-senju-museum": "img/DcYZqIYGGrz.webp",
 "p-karimoku-research-center": "img/DZLfbS1TSX2.webp",
 "p-katayama-bunzaburo-shoten-kyoto-honten": "img/DbTs5pAzMMH.webp",
 "p-kyocera-museum-of-art": "img/DcYZqIYGGrz.webp",
 "p-maison-hermes-ginza": "img/DbQMKjbzURT.webp",
 "p-nezu-museum": "img/DcYZqIYGGrz.webp",
 "p-oedo-antique-market": "img/Db-y_xbiEaq.webp",
 "p-reiyukai-shakaden-temple": "img/Db-y_xbiEaq.webp",
 "p-soma-pastry-shop": "img/DcSFLx9JD7x.webp",
 "p-spo-cha": "img/Dbgc1DlOYtw.webp",
 "p-taro-okamoto-memorial-museum": "img/DcYZqIYGGrz.webp",
 "p-teshima-art-museum": "img/DcYZqIYGGrz.webp",
 "p-the-national-art-center": "img/DcYZqIYGGrz.webp",
 "p-tokyo-tower": "img/DbTLepZTZtL.webp",
 "p-towada-art-center": "img/DcSFLx9JD7x.webp",
 "p-tsukiji-uogashi": "img/DZuPponRWVl.webp",
 "p-uniqlo-ginza": "img/DZf2nvBMdAx.webp",
 "p-yoyogi-national-gymnasium": "img/Db-y_xbiEaq.webp"
};
